export const reactions = [
    {
        id: 1,
        name: 'Like',
        emoji: '👍',
    },
    {
        id: 2,
        name: 'Love',
        emoji: '❤️',
    },
    {
        id: 3,
        name: 'Haha',
        emoji: '😂',
    },
    {
        id: 4,
        name: 'Wow',
        emoji: '😮',
    },
    {
        id: 5,
        name: 'Sad',
        emoji: '😥',
    },
    {
        id: 6,
        name: 'Angry',
        emoji: '😡',
    },
];

export const userContentReactions = [
    {
        id: 1,
        userId: 20,
        reactionId: 3,
        contentId: 1,
    },
    {
        id: 2,
        userId: 30,
        reactionId: 2,
        contentId: 1,
    },
    {
        id: 4,
        userId: 14,
        reactionId: 4,
        contentId: 1,
    },
    {
        id: 7,
        userId: 8,
        reactionId: 5,
        contentId: 1,
    },
    {
        id: 8,
        userId: 20,
        reactionId: 2,
        contentId: 1,
    },
    {
        id: 9,
        userId: 23,
        reactionId: 6,
        contentId: 1,
    },
    {
        id: 10,
        userId: 11,
        reactionId: 5,
        contentId: 1,
    },
    {
        id: 11,
        userId: 21,
        reactionId: 6,
        contentId: 1,
    },
    {
        id: 13,
        userId: 12,
        reactionId: 3,
        contentId: 1,
    },
    {
        id: 14,
        userId: 4,
        reactionId: 5,
        contentId: 1,
    },
    {
        id: 15,
        userId: 12,
        reactionId: 5,
        contentId: 1,
    },
    {
        id: 17,
        userId: 9,
        reactionId: 2,
        contentId: 1,
    },
    {
        id: 21,
        userId: 10,
        reactionId: 4,
        contentId: 1,
    },
    {
        id: 24,
        userId: 25,
        reactionId: 5,
        contentId: 1,
    },
    {
        id: 25,
        userId: 25,
        reactionId: 1,
        contentId: 1,
    },
    {
        id: 27,
        userId: 23,
        reactionId: 3,
        contentId: 1,
    },
    {
        id: 28,
        userId: 11,
        reactionId: 2,
        contentId: 1,
    },
    {
        id: 29,
        userId: 10,
        reactionId: 1,
        contentId: 1,
    },
];

export const users = [
    {
        id: 1,
        firstName: 'Lizette',
        lastName: 'Phippen',
        email: 'lphippen0@berkeley.edu',
        avatar: 'http://dummyimage.com/128x134.png/dddddd/000000',
    },
    {
        id: 2,
        firstName: 'Garreth',
        lastName: 'Heikkinen',
        email: 'gheikkinen1@naver.com',
        avatar: 'http://dummyimage.com/147x121.png/ff4444/ffffff',
    },
    {
        id: 3,
        firstName: 'Jacky',
        lastName: 'Turbefield',
        email: 'jturbefield2@google.de',
        avatar: 'http://dummyimage.com/116x202.png/cc0000/ffffff',
    },
    {
        id: 4,
        firstName: 'Arman',
        lastName: "O'Scanlon",
        email: 'aoscanlon3@bloomberg.com',
        avatar: 'http://dummyimage.com/224x111.png/dddddd/000000',
    },
    {
        id: 5,
        firstName: 'Truman',
        lastName: 'Disbury',
        email: 'tdisbury4@51.la',
        avatar: 'http://dummyimage.com/117x146.png/cc0000/ffffff',
    },
    {
        id: 6,
        firstName: 'Lizzy',
        lastName: 'Kofax',
        email: 'lkofax5@netvibes.com',
        avatar: 'http://dummyimage.com/221x200.png/5fa2dd/ffffff',
    },
    {
        id: 7,
        firstName: 'Mace',
        lastName: 'Burg',
        email: 'mburg6@washington.edu',
        avatar: 'http://dummyimage.com/103x204.png/dddddd/000000',
    },
    {
        id: 8,
        firstName: 'Luca',
        lastName: 'Weatherall',
        email: 'lweatherall7@exblog.jp',
        avatar: 'http://dummyimage.com/172x191.png/ff4444/ffffff',
    },
    {
        id: 9,
        firstName: 'Horatia',
        lastName: 'Walduck',
        email: 'hwalduck8@delicious.com',
        avatar: 'http://dummyimage.com/109x226.png/dddddd/000000',
    },
    {
        id: 10,
        firstName: 'Sadella',
        lastName: 'Lack',
        email: 'slack9@bing.com',
        avatar: 'http://dummyimage.com/153x172.png/ff4444/ffffff',
    },
    {
        id: 11,
        firstName: 'Dagny',
        lastName: 'Zorzoni',
        email: 'dzorzonia@nbcnews.com',
        avatar: 'http://dummyimage.com/120x218.png/cc0000/ffffff',
    },
    {
        id: 12,
        firstName: 'Tisha',
        lastName: 'Polsin',
        email: 'tpolsinb@usnews.com',
        avatar: 'http://dummyimage.com/153x110.png/5fa2dd/ffffff',
    },
    {
        id: 13,
        firstName: 'Wanids',
        lastName: 'Winspar',
        email: 'wwinsparc@indiatimes.com',
        avatar: 'http://dummyimage.com/200x116.png/5fa2dd/ffffff',
    },
    {
        id: 14,
        firstName: 'Arte',
        lastName: 'Balstone',
        email: 'abalstoned@e-recht24.de',
        avatar: 'http://dummyimage.com/200x248.png/ff4444/ffffff',
    },
    {
        id: 15,
        firstName: 'Ekaterina',
        lastName: 'Quinet',
        email: 'equinete@alexa.com',
        avatar: 'http://dummyimage.com/143x214.png/5fa2dd/ffffff',
    },
    {
        id: 16,
        firstName: 'Riobard',
        lastName: 'Golder',
        email: 'rgolderf@wix.com',
        avatar: 'http://dummyimage.com/101x147.png/dddddd/000000',
    },
    {
        id: 17,
        firstName: 'Hyacinthia',
        lastName: 'Drakeford',
        email: 'hdrakefordg@army.mil',
        avatar: 'http://dummyimage.com/119x142.png/cc0000/ffffff',
    },
    {
        id: 18,
        firstName: 'June',
        lastName: 'Vedishchev',
        email: 'jvedishchevh@tiny.cc',
        avatar: 'http://dummyimage.com/112x182.png/ff4444/ffffff',
    },
    {
        id: 19,
        firstName: 'Rance',
        lastName: 'Ferre',
        email: 'rferrei@craigslist.org',
        avatar: 'http://dummyimage.com/227x132.png/5fa2dd/ffffff',
    },
    {
        id: 20,
        firstName: 'Geordie',
        lastName: 'Maccaddie',
        email: 'gmaccaddiej@ftc.gov',
        avatar: 'http://dummyimage.com/194x110.png/ff4444/ffffff',
    },
    {
        id: 21,
        firstName: 'Salomo',
        lastName: 'Bucknell',
        email: 'sbucknellk@is.gd',
        avatar: 'http://dummyimage.com/132x206.png/dddddd/000000',
    },
    {
        id: 22,
        firstName: 'Hildegaard',
        lastName: 'Bowick',
        email: 'hbowickl@java.com',
        avatar: 'http://dummyimage.com/168x157.png/dddddd/000000',
    },
    {
        id: 23,
        firstName: 'Sloane',
        lastName: 'Smeal',
        email: 'ssmealm@live.com',
        avatar: 'http://dummyimage.com/110x197.png/dddddd/000000',
    },
    {
        id: 24,
        firstName: 'Violette',
        lastName: 'Sprasen',
        email: 'vsprasenn@hibu.com',
        avatar: 'http://dummyimage.com/220x249.png/5fa2dd/ffffff',
    },
    {
        id: 25,
        firstName: 'Pansie',
        lastName: 'Awcock',
        email: 'pawcocko@artisteer.com',
        avatar: 'http://dummyimage.com/235x221.png/5fa2dd/ffffff',
    },
    {
        id: 26,
        firstName: 'Nils',
        lastName: 'Varian',
        email: 'nvarianp@nasa.gov',
        avatar: 'http://dummyimage.com/163x177.png/ff4444/ffffff',
    },
    {
        id: 27,
        firstName: 'Loy',
        lastName: 'Trounce',
        email: 'ltrounceq@icq.com',
        avatar: 'http://dummyimage.com/182x144.png/dddddd/000000',
    },
    {
        id: 28,
        firstName: 'Erma',
        lastName: 'Breslane',
        email: 'ebreslaner@canalblog.com',
        avatar: 'http://dummyimage.com/108x140.png/cc0000/ffffff',
    },
    {
        id: 29,
        firstName: 'Prentiss',
        lastName: 'Justice',
        email: 'pjustices@blinklist.com',
        avatar: 'http://dummyimage.com/247x171.png/dddddd/000000',
    },
    {
        id: 30,
        firstName: 'Addia',
        lastName: 'Feehan',
        email: 'afeehant@howstuffworks.com',
        avatar: 'http://dummyimage.com/119x131.png/ff4444/ffffff',
    },
];
